/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package IntroToProgramming;

class Library { 
    public static void main(String[] args) { 

    	int i = 1;
    	while(i <= 10) {
    		System.out.print(i++);
    	}
    	
    	System.out.println();
    	
    	for(int n = 1; n <=10; n++) {
    		System.out.print(n);
    	}

    	System.out.println();
    	int n = 1;
    	while (n <= 20) {
    		n = n * 2;
    		System.out.print(n);
    	}
 	} 
} 

